server:
  port: 9005
  tomcat:
    max-threads: 1
mybatis:
  mapper-locations: classpath*:mapper/*.xml


redis:
  host: 101.34.230.245
  port: 6379
  password: f93889rfx88
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: panther
    driver-class-name: com.mysql.cj.jdbc.Driver