server:
  port: 9005
  tomcat:
    max-threads: 1
mybatis:
  mapper-locations: classpath*:mapper/*.xml


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: panther
    driver-class-name: com.mysql.cj.jdbc.Driver
